In [21]:
import tensorflow as tf
import numpy as np
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.datasets import mnist, fashion_mnist
from tensorflow.keras import layers, models

# Define VGG16 architecture for MNIST
def vgg16():
    model = Sequential()

    # Block 1
    model.add(Conv2D(64, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 1)))
    model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
    model.add(MaxPooling2D((2, 2), strides=(2, 2)))

    # Block 2
    model.add(Conv2D(128, (3, 3), activation='relu', padding='same'))
    model.add(Conv2D(128, (3, 3), activation='relu', padding='same'))
    model.add(MaxPooling2D((2, 2), strides=(2, 2)))

    # Block 3
    model.add(Conv2D(256, (3, 3), activation='relu', padding='same'))
    model.add(Conv2D(256, (3, 3), activation='relu', padding='same'))
    model.add(Conv2D(256, (3, 3), activation='relu', padding='same'))
    model.add(MaxPooling2D((2, 2), strides=(2, 2)))

   # Block 4
    model.add(Conv2D(512, (3, 3), activation='relu', padding='same'))
    model.add(Conv2D(512, (3, 3), activation='relu', padding='same'))
    model.add(Conv2D(512, (3, 3), activation='relu', padding='same'))
    model.add(MaxPooling2D((2, 2), strides=(2, 2)))

     # Block 5
    model.add(Conv2D(512, (3, 3), activation='relu', padding='same'))
    model.add(Conv2D(512, (3, 3), activation='relu', padding='same'))
    model.add(Conv2D(512, (3, 3), activation='relu', padding='same'))
   # model.add(MaxPooling2D((2, 2), strides=(2, 2)))


    # Flatten and fully connected layers
    model.add(Flatten())
    model.add(Dense(4096, activation='relu'))
    model.add(Dense(4096, activation='relu'))
    model.add(Dense(10, activation='softmax'))  # Output layer with 10 units for 10 classes (digits 0-9)

    return model

# Create the VGG16 model for MNIST
model = vgg16()

# Display the model summary
model.summary()


Model: "sequential_15"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_144 (Conv2D)         (None, 28, 28, 64)        640       
                                                                 
 conv2d_145 (Conv2D)         (None, 28, 28, 64)        36928     
                                                                 
 max_pooling2d_52 (MaxPooli  (None, 14, 14, 64)        0         
 ng2D)                                                           
                                                                 
 conv2d_146 (Conv2D)         (None, 14, 14, 128)       73856     
                                                                 
 conv2d_147 (Conv2D)         (None, 14, 14, 128)       147584    
                                                                 
 max_pooling2d_53 (MaxPooli  (None, 7, 7, 128)         0         
 ng2D)                                               

In [ ]:
# Load MNIST dataset
(x_train_m, y_train_m), (x_test_m, y_test_m) = mnist.load_data()


# Preprocess the data
# Normalize pixel values to be between 0 and 1
x_train_m= x_train_m / 255.0
x_test_m = x_test_m / 255.0

# Convert labels to categorical format
y_train_m= to_categorical(y_train_m, 10)
y_test_m = to_categorical(y_test_m, 10)

# Compile and train the model
model_m = vgg16()
model_m.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model_m.fit(x_train_m, y_train_m, validation_data=(x_test_m, y_test_m), epochs=2, batch_size=200, verbose=True)


Epoch 1/2
 17/300 [>.............................] - ETA: 49:38 - loss: 2.3041 - accuracy: 0.0982

In [18]:
# Evaluate the model on MNIST testing samples
y_pred_m = model_m.predict(x_test_m)
y_pred_classes_m = np.argmax(y_pred_m, axis=1)
y_true_m = np.argmax(y_test_m, axis=1)

# Compute confusion matrix, precision, recall, and F1 score
confusion_m = confusion_matrix(y_true_m, y_pred_classes_m)
precision_m = precision_score(y_true_m, y_pred_classes_m, average='weighted')
recall_m = recall_score(y_true_m, y_pred_classes_m, average='weighted')
f1_m = f1_score(y_true_m, y_pred_classes_m, average='weighted')

print("Confusion Matrix (MNIST):")
print(confusion_m)
print(f"Precision (MNIST): {precision_m}")
print(f"Recall (MNIST): {recall_m}")
print(f"F1 Score (MNIST): {f1_m}")

313/313 [==============================] - 51s 163ms/step
Confusion Matrix (MNIST):
[[ 979    0    0    0    0    0    0    1    0    0]
 [   0 1132    0    3    0    0    0    0    0    0]
 [   1    0 1031    0    0    0    0    0    0    0]
 [   0    0    1 1007    0    1    0    0    1    0]
 [   0    0    1    0  979    0    0    0    0    2]
 [   1    0    0    8    0  882    1    0    0    0]
 [   9    2    0    1    3    0  943    0    0    0]
 [   0    2    5    0    0    0    0 1020    0    1]
 [   3    0    1    3    0    0    0    0  966    1]
 [   1    0    1    0    7    0    0    2    1  997]]
Precision (MNIST): 0.9936446872793713
Recall (MNIST): 0.9936
F1 Score (MNIST): 0.9936006348524965


In [ ]:
# Load Fashion MNIST dataset
(x_train_f, y_train_f), (x_test_f, y_test_f) = fashion_mnist.load_data()

# Preprocess the data
# Normalize pixel values to be between 0 and 1
x_train_f= x_train_f / 255.0
x_test_f = x_test_f / 255.0

# Convert labels to categorical format
y_train_f= to_categorical(y_train_f, 10)
y_test_f= to_categorical(y_test_f, 10)

# Compile and train the model
model_f = vgg16()
model_f.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model_f.fit(x_train_f, y_train_f, validation_data=(x_test_f, y_test_f), epochs=2, batch_size=200, verbose=True)

In [ ]:
# Evaluate the model on Fashion MNIST testing samples
y_pred_f = model_f.predict(x_test_f)
y_pred_classes_f= np.argmax(y_pred_f, axis=1)
y_true_f = np.argmax(y_test_f, axis=1)


# Compute confusion matrix, precision, recall, and F1 score
confusion_f= confusion_matrix(y_true_f, y_pred_classes_f)
precision_f = precision_score(y_true_f y_pred_classes_f, average='weighted')
recall_f = recall_score(y_true_f, y_pred_classes_f, average='weighted')
f1_f = f1_score(y_true_f, y_pred_classes_f, average='weighted')

print("(Fashion MNIST):")
print("Confusion Matrix :")
print(confusion_f)
print(f"Precision : {precision_f}")
print(f"Recall : {recall_f}")
print(f"F1 Score : {f1_f}")